sonar.projectKey=CauehCraft_AutoDroid-Studio
sonar.organization=cauehcraft
sonar.sources=src
sonar.python.version=3.10
sonar.exclusions=venv/**, **/*.pyc, scrcpy-win64/**, assets/**
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
